services:
  - type: web
    name: Multimodal-AI-for-Retail-Product-Insights
    env: python
    branch: main
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn src.api:app
    plan: free
    autoDeploy: true
